language: cpp

cache: ccache

notifications:
  email:
    on_success: never
    on_failure: always
    
matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=57
  - os: osx
    compiler: clang
    env:
     - QT_BASE=57

before_install:

  - if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521-trusty -y; fi
  - if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - if [[ "$QT_BASE" = "55" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [ "$QT_BASE" = "52" ]; then sudo apt-get install -qq qt52base; source /opt/qt52/bin/qt52-env.sh; fi
  - if [ "$QT_BASE" = "53" ]; then sudo apt-get install -qq qt53base; source /opt/qt53/bin/qt53-env.sh; fi
  - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base; source /opt/qt54/bin/qt54-env.sh; fi
  - if [ "$QT_BASE" = "55" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
        sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh; 
      else
        brew install qt55;
        brew link --force qt55;
      fi
    fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
        sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; 
      else
        brew install qt5;
        brew link --force qt5;
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      wget https://github.com/trevorsandy/lpub3d/releases/download/v2.0.0/test001.zip -O complete.zip;
      mv complete.zip /Users/travis/build/trevorsandy/lpub3d/mainApp/extras/complete.zip;
      wget https://github.com/trevorsandy/lpub3d/releases/download/v2.0.0/test002.zip -O lpub3dldrawunf.zip;
      mv lpub3dldrawunf.zip /Users/travis/build/trevorsandy/lpub3d/mainApp/extras/lpub3dldrawunf.zip;
    fi
    
script:
  - qmake -v
  - qmake -r
  - make
  - unset QT_PLUGIN_PATH
  - unset LD_LIBRARY_PATH
  - unset QTDIR
  - # Possibly need to set LD_LIBRARY_PATH to the extracted location of the dummy deb
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get -y install checkinstall ;
      sudo checkinstall --pkgname=app --pkgversion="1" --backup=no --fstrans=no --default --deldoc ;
      ls ;
      mkdir appdir ; cd appdir ;
      dpkg -x ../app_1-1_amd64.deb . ; find . ;
      cp ./usr/share/applications/lpub3d.desktop . ;
      cp ./usr/share/pixmaps/lpub3d.png . ;
      wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" ;
      chmod a+x linuxdeployqt*.AppImage ;
      ./linuxdeployqt*.AppImage ./usr/bin/lpub3d10 ;
      ./linuxdeployqt*.AppImage ./usr/bin/lpub3d10 -appimage ;
    fi
